import NavBar from "./components/Nav";
import "./globals.css";
import TempRun from "./temp/page";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {



  return (
    <html lang="en" >
      <body>
        <NavBar />
        {children}
        <TempRun />
      </body>
    </html>
  );
}
